#!/bin/bash

# Doppler Manager - Emergency Seal Protocol
# Executed when a secret leak is suspected or confirmed
# This script captures audit evidence and generates incident documentation

set -euo pipefail

# Configuration
AUDIT_DIR="${DOPPLER_AUDIT_DIR:-${HOME}/.cache/doppler-manager}"
INCIDENT_DIR="${AUDIT_DIR}/incidents"
INCIDENT_ID="INC-$(date +%Y%m%d-%H%M%S)-$$"

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

error() { echo -e "${RED}[CRITICAL]${NC} $1" >&2; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

# Ensure directories exist
mkdir -p "$INCIDENT_DIR"

echo "=============================================="
echo "  Emergency Seal Protocol Initiated"
echo "=============================================="
echo ""
error "SECRET LEAK INCIDENT DETECTED"
echo "Incident ID: $INCIDENT_ID"
echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo ""

# Step 1: Capture current audit trail
echo "[1/5] Capturing audit trail..."
AUDIT_SNAPSHOT="${INCIDENT_DIR}/${INCIDENT_ID}-audit.jsonl"
if [[ -f "${AUDIT_DIR}/audit.log" ]]; then
    cp "${AUDIT_DIR}/audit.log" "$AUDIT_SNAPSHOT"
    echo "  Captured: $AUDIT_SNAPSHOT ($(wc -l < "$AUDIT_SNAPSHOT") entries)"
else
    touch "$AUDIT_SNAPSHOT"
    echo "  No existing audit log found"
fi
echo ""

# Step 2: Capture alert history
echo "[2/5] Capturing alert history..."
ALERT_SNAPSHOT="${INCIDENT_DIR}/${INCIDENT_ID}-alerts.jsonl"
if [[ -f "${AUDIT_DIR}/alerts.log" ]]; then
    cp "${AUDIT_DIR}/alerts.log" "$ALERT_SNAPSHOT"
    echo "  Captured: $ALERT_SNAPSHOT ($(wc -l < "$ALERT_SNAPSHOT") entries)"
else
    touch "$ALERT_SNAPSHOT"
    echo "  No existing alerts found"
fi
echo ""

# Step 3: Capture current environment state
echo "[3/5] Capturing environment state..."
ENV_SNAPSHOT="${INCIDENT_DIR}/${INCIDENT_ID}-environment.json"

env_json=$(cat <<EOF
{
  "incident_id": "$INCIDENT_ID",
  "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "hostname": "$(hostname 2>/dev/null || echo "unknown")",
  "user": "$(whoami 2>/dev/null || echo "unknown")",
  "cwd": "$(pwd)",
  "doppler_configured": $(command -v doppler &> /dev/null && echo "true" || echo "false"),
  "shell_history_files": [
    "$HOME/.bash_history",
    "$HOME/.zsh_history"
  ],
  "env_files_found": $(find . -maxdepth 3 -name ".env" -type f 2>/dev/null | grep -v node_modules | head -5 | json -a 2>/dev/null || echo "[]")
}
EOF
)
echo "$env_json" > "$ENV_SNAPSHOT"
echo "  Captured: $ENV_SNAPSHOT"
echo ""

# Step 4: Generate incident report
echo "[4/5] Generating incident report..."
REPORT_FILE="${INCIDENT_DIR}/${INCIDENT_ID}-report.md"

cat > "$REPORT_FILE" <<EOF
# Secret Leak Incident Report

## Incident Details

| Field | Value |
|-------|-------|
| **Incident ID** | $INCIDENT_ID |
| **Timestamp** | $(date -u +"%Y-%m-%dT%H:%M:%SZ") |
| **Hostname** | $(hostname 2>/dev/null || echo "unknown") |
| **User** | $(whoami 2>/dev/null || echo "unknown") |
| **Working Directory** | $(pwd) |

## Immediate Actions Required

### 1. Secret Rotation (MANDATORY)
The affected secret(s) MUST be rotated immediately:

1. Log into Doppler Dashboard: https://dashboard.doppler.com
2. Navigate to the affected project and config
3. Rotate the compromised secret(s)
4. Update all services that use the secret

### 2. Access Review
Review who has accessed the affected secrets:
- Check Doppler access logs in the dashboard
- Verify no unauthorized access occurred

### 3. Environment Cleanup
Check for and remove any secret contamination:
\`\`\`bash
# Remove any .env files that may contain the secret
find . -name ".env" -type f

# Clear shell history if secrets were typed
history -c

# Review any scripts that may have logged secrets
grep -r "SECRET_NAME" --include="*.log" .
\`\`\`

## Evidence Files

- Audit log: \`${INCIDENT_ID}-audit.jsonl\`
- Alerts: \`${INCIDENT_ID}-alerts.jsonl\`
- Environment: \`${INCIDENT_ID}-environment.json\`

## Classification

**Severity**: [ ] LOW  [ ] MEDIUM  [ ] HIGH  [ ] CRITICAL

**Secret Type**: [ ] API Key  [ ] Password  [ ] Token  [ ] Other

**Exposure**: [ ] Internal Only  [ ] External Possible  [ ] Confirmed External

---

*Generated by Doppler Manager Emergency Seal Protocol*
*For internal security use only*
EOF
echo "  Generated: $REPORT_FILE"
echo ""

# Step 5: Clear sensitive data from audit (optional, preserve evidence)
echo "[5/5] Preserving evidence (audit logs NOT cleared)..."
echo "  Evidence preserved for forensic analysis"
echo ""

# Summary
echo "=============================================="
echo "  Emergency Protocol Complete"
echo "=============================================="
echo ""
echo "IMPORTANT NEXT STEPS:"
echo ""
echo "1. ROTATE the affected secret(s) in Doppler Dashboard"
echo ""
echo "2. Review the incident report: $REPORT_FILE"
echo ""
echo "3. Check Doppler access logs to verify no unauthorized use"
echo ""
echo "4. If secret was committed to git, follow git-secrets recovery"
echo ""
warn "Do NOT ignore this incident - secret rotation is MANDATORY"
echo ""
echo "Evidence stored in: $INCIDENT_DIR"
echo "Incident ID for reference: $INCIDENT_ID"